#!/bin/bash
set -e

# Sync idempotency.feature from website repo
# Canonical source: https://github.com/idempot-dev/website

URL="https://raw.githubusercontent.com/idempot-dev/website/main/docs/specs/idempotency.feature"
TARGET="tests/spec/idempotency.feature"

# Create header comment with sync metadata
cat > "$TARGET" << 'HEADER'
# AUTO-GENERATED: Synced from idempot-dev/website
# Source: https://github.com/idempot-dev/website/blob/main/docs/specs/idempotency.feature
# Do not edit this file directly. Run: pnpm run spec:sync
#
HEADER

# Append the actual feature file content
curl -sL "$URL" >> "$TARGET"

echo "Spec synced from website repo to $TARGET"
